name: mitch
favicon: null
layout_spectrum: 0.46638
typography_spectrum: 0.41811
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#6b631c'
    - '#1d1918'
    - '#fefa8d'
    - '#bd9a2b'
    - '#a0afc7'
  brandStrength: 0.5
  lightness: 0.4375
  saturation: 0.375
  rhythmicContrast: 0.75
purpose: []
