name: mitch
favicon: null
layout_spectrum: 0.8656462572980672
typography_spectrum: 0.4500489521306008
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.41294418345205486
  lightness: 0.40661191451363266
  saturation: 0.1964436660055071
  rhythmicContrast: 0.7157830158248544
purpose: []
